import './globals.css'
import type { Metadata } from 'next'
import { Noto_Sans_JP } from "next/font/google";
import { cn } from "@/lib/utils";

const fontNotoSansJp = Noto_Sans_JP({
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "ブログ投稿",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ja">
      {/* font-smoothing: antialiased;
      SafariやFirefox向けのアンチエイリアス処理を指定します。
      animationでフォントがピクピクする不具合は、下記で解消する可能性があります。 */}
      <body
        className={cn('bg-background antialiased min-h-screen',
        fontNotoSansJp.className
        )}
      >
        {children}
      </body>
    </html>
  )
}
